#SOPLEX_INCLUDE=/common/home/jk1849/soplex-4.0.1/src
#SOPLEX_LIB=/common/home/jk1849/soplex-4.0.1/build/lib/libsoplex.a

all:

sorting:
	g++ -o sorting sorting.cpp -lmpfr -lgmp

constgen:
	g++ -o constgen constgen.cpp -lmpfr -lgmp -lm
